version: "3.8"
services:
  postgraphile:
    container_name: postgraphile
    build:
      context: .
      dockerfile: postgraphile.Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: postgres
    image: postgres:15
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - "/var/lib/postgresql/data"
      - "./migrations:/docker-entrypoint-initdb.d"
    command:
      - postgres
      - -c
      - wal_level=logical
      - -c
      - shared_preload_libraries=pg_stat_statements
    healthcheck:
      test: ["CMD-SHELL", "PGUSER=postgres", "pg_isready"]
      interval: 1s
      timeout: 10s
      retries: 5
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
