
fragment bookSelect on Book{
  bookId
  publicationDate
  title
  authorByAuthorId {
      name
  }
}

fragment bookReviewSelect on BookReview{
      reviewId
      starReview
      textReview
      bookByBookId {
        ...bookFields
      }
}

query getAllBooks {
  allBooks {
    nodes {
      ...bookFields
    }
  }
}

mutation createBookReview {
  createBookReview(
    input: {
      bookReview: { textReview: "awesome", starReview: "4.9", bookId: 1 }
    }
  ) {
    bookReview {
      ...bookReviewSelect
    }
  }
}

query getAllBookReviews {
  allBookReviews {
    edges {
      node {
        ...bookReviewSelect
      }
    }
  }
}